<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
		<string>jsx</string>
		<string>ts</string>
		<string>tsx</string>
		<string>vue</string>
		<string>svelte</string>
	</array>
	<key>injectionSelector</key>
	<string>L:source -string -comment</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\s*+(?:(?:(Relay)\??\.)(QL)|(gql|graphql|graphql\.experimental)|(/\* GraphQL \*/))\s*(`)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.class.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tagged-template.js</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tagged-template.js</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.graphql.js</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.template.begin.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.block.graphql</string>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.template.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.graphql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(`)(#graphql)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.template.begin.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.graphql.js</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.block.graphql</string>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.template.end.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>taggedTemplates</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.graphql</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>inline.graphql</string>
</dict>
</plist>
